### ISSUE TITLE
🔧 Change metrics format so the repo/project is part of the reported metric

### ISSUE THREAD

**Issue by Nicoretti** [exasol/python-toolbox#120]
# Summary
To enhance the identification and self-containment of the metrics, they should include information about their originating project.

# Details
The current data format is:
```json
{
  "commit": "38cef0d0b86fd9fcd042d874af5ebc6a17e937d1",
  "date": "2023-12-18 07:19:14.687615",
  "coverage": 26.629422718808193,
  "maintainability": "B",
  "reliability": "N/A",
  "security": "N/A",
  "technical_debt": "N/A"
}
```

The proposed enhancement involves adding a project field. After updating, remember to release a new schema version at https://github.com/exasol/schemas.

# Background & Context
Schema Repository: https://github.com/exasol/schemas
Relevant Discussion: https://github.com/exasol/github-issue-adapter/pull/223#discussion_r1456964783

```json
{
  "project": "python-toolbox",
  "commit": "38cef0d0b86fd9fcd042d874af5ebc6a17e937d1",
  "date": "2023-12-18 07:19:14.687615",
  "coverage": 26.629422718808193,
  "maintainability": "B",
  "reliability": "N/A",
  "security": "N/A",
  "technical_debt": "N/A"
}
```
# Tasks
- [x] Incorporate the project field into the metrics format.
- [ ]  Update and test the modified schema.
- [x]  Release a new version of the schema on [exasol/schemas](https://github.com/exasol/schemas).
- [x]  Update relevant documentation and changelog.

**Comment by Nicoretti** [comment]
Has been already implemented see https://github.com/exasol/python-toolbox/pull/158
