### ISSUE TITLE
✨ Check and fix marking the version file as "generated" in file .gitattributes

### ISSUE THREAD

**Issue by ckunki** [exasol/python-toolbox#192]
# Summary

This ticket requests to mark the version file as "generated" in file `.gitattributes`.

# Details

This could be implemented in method `fix()` In file `exasol/toolbox/nox/_format.py`.

Result could be like

```
version.py   linguist-generated
```

## Background & Context

Reviewers can ignore generated files and focus on manual changes, making reviews easier, reducing effort for reviews and focusing on important changes. 

## Examples

See https://github.com/exasol/project-keeper/blob/main/.gitattributes

## References

See https://github.com/exasol/project-keeper/

# Task(s)

- [ ] Create parser for file `.gitattributes`
- [ ] Update method `fix()` In file `exasol/toolbox/nox/_format.py`.
  - [ ] Check if version file is contained already 
  - [ ] If not, then add the file 
- [ ] update method `check()` in `exasol/toolbox/nox/tasks.py`, too, reporting if version file is not marked as generated.
