### ISSUE TITLE
📚 Improve documentation

### ISSUE THREAD

**Issue by ckunki** [exasol/python-toolbox#27]
# Summary
Make documentation more accessible for developers which are not in depth familiar with the language and tooling. 

## Tasks
- [x] Add package description to project metadata (`pyproject.toml`)
- [x] ~Mention requirement to `install poetry` in documentation~
- [x] Mention workspace layout and standard tools (poetry, nox, etc.) in documentation, or link to toolbox
       (mention cookiecutter)
- [x] Describe default/standard folder structure for tests
       (mention cookiecutter)
- [x] ~Mention `noxfile.py` and its purpose earlier in documentation (optional)~
- [x] Mention `noxconfig.py` and its purpose earlier in documentation (optional)
- [x] ~Document how mypy, docs etc. could be bypassed/customized if needed~
