### ISSUE TITLE
✨  Add command to generate & update config files

### ISSUE THREAD

**Issue by Nicoretti** [exasol/python-toolbox#62]
# Summary
In order to simplify setting up and maintaining a project with the `python-toolbox`, a command for managing
the configuration files would be helpful. 

# Details
Having a cli tool for this task will reduce the need of `copy & paste` and replacing dummy values.

TL;DR:
* Simplifies the workflow
* Reduces the amount of potential errors
* Reduces the effort for setting up and keeping up to date with the toolbox

## Examples

Generate nox config file(s)
```shell
tbox config generate nox
tbox config generate noxconfig
```
Update the tool configuration(s) in the `pyproject.toml` file

```shell
tbox config update pyproject
```

# References & Context
* https://exasol.github.io/python-toolbox/user_guide/getting_started.html

# Task(s)
- [ ] Add command to generate standard `noxconfig.py`
- [ ] Add command to generate standard `noxfile.py` 
- [ ] Add command to update `pyproject.toml` with the expected tooling settings
    - [ ] pylint
    - [ ] coverage
    - [ ] black
    - [ ] isort
    - [ ] ...
- [ ] Update documentation
- [ ] Update change log
