### ISSUE TITLE
✨ Add command to install or update a vagrant development environment

### ISSUE THREAD

**Issue by tkilias** [exasol/python-toolbox#69]
# Summary

Add a command line command which allows a user to install or update a vagrant development environment from templates managed in this project. 

# Details
- We already have some copies of a prototype https://github.com/exasol/integration-test-docker-environment/tree/main/vagrant
- We should deliver with this project a core setup for the development environment
- However, each repository might need to extend it
  - This means we need a way, how each repository can inject its extension
- Currently, we use bash scripts for the basic setup, which can be annoying to maintain, maybe we should move to ansible
- We should support libvirt (linux), virtualbox (MacOSX) and hyperv (Windows), if possible, these are the hypervisors used by our team

## Background & Context

- A vagrant development environment helps with setting up a Virtual Machine with all dependencies necessary to run and test your code. 
  - This is especially necessary, if you need to interact with docker and your host system doesn't provide docker. 
  - Furthermore, in case you break something in your current VM, you simply destroy it and start a new one, without the tedious setup process.
- We already have multiple copies of this in many repositories, and maintaining all them is tedious. 

## Examples

- https://github.com/exasol/integration-test-docker-environment/tree/main/vagrant

## References
- https://developer.hashicorp.com/vagrant/docs
- https://github.com/exasol/script-languages-release/blob/master/doc/user_guide/vagrant.md
- https://github.com/vagrant-libvirt/vagrant-libvirt

# Task(s)
- [] Add core templates
- [] Develop extension mechanism
- [] Refactor setup scripts
- [] Add hypervisors

**Comment by tkilias** [comment]
List of improvements:

- https://github.com/exasol/advanced-analytics-framework/pull/106/files/ff0006d860fe36fbe3a874d977ff5386fc7bd2c0#r1219270868
