### ISSUE TITLE
✨ Add security linter to the toolbox

### ISSUE THREAD

**Issue by Nicoretti** [exasol/python-toolbox#74]
# Summary
Add a security scanner and target to the toolbox features.

## Open Questions

* Should this be mandatory, or should a project be able to enable or disable it?
* Are there other alternatives?
* How and if should this be in the CI? (Projects need to be fixed first)
* How to define exceptions for specific code parts (functions, files) in a project?

## References
* [Bandit](https://github.com/PyCQA/bandit)
* #73 

# Task(s)
```[tasklist]
- [ ] Add bandit as security linter
- [ ] Add a target checking for security issues
- [ ] Update/Add documentation
- [ ] Update changelog
```

**Comment by redcatbear** [comment]
Does not work on Janis Windows box. Need to exchange.
