### ISSUE TITLE
✨ Add support for project license auditing 

### ISSUE THREAD

**Issue by Nicoretti** [exasol/python-toolbox#75]
# Summary
Add support to scan the project(s) license compliance.

# Details
Make sure to distinguish or `build/dev` dependencies etc from the dependencies used by the `library/application`. 

## Background & Context
Adding such a nox target will simplify validation of appropriate dependency usage in regard to the project(s) and their licenses.

## References
* [pip-licenses](https://pypi.org/project/pip-licenses/)
* [Is a program that forks a GPL-licensed program via a system or vice versa call derivative work?](https://www.ifross.org/?q=en/program-forks-gpl-licensed-program-system-or-vice-versa-call-derivative-work)
* [License compatibility](https://en.wikipedia.org/wiki/License_compatibility)
* [Open Source Licenses and their Compatibility](https://janelia-flyem.github.io/licenses.html)
* [License Compatibility and Relicensing](https://www.gnu.org/licenses/license-compatibility.en.html)
* [license-list](https://www.gnu.org/licenses/license-list.en.html)

# Task(s)
```[tasklist]
- [x] Reconsider/Evaluate license used for toolbox and/or it's dependencies
- [x] Add nox target for checking the license compliance
- [x] Add configuration settings, so each project can specify allowed list
- [ ] Add license auditing to CI
- [ ] Add test(s)
- [ ] Update documentation
- [ ] Update changelog
```

**Comment by Nicoretti** [comment]
> Reconsider/Evaluate license used for toolbox and/or it's dependencies

@tkilias  and @Nicoretti  concluded to  keep MIT license. Based on the following reasoning:

* The toolkit should not push a less permissive license downstream
* Pylint is only used as CLI (and mostly in dev builds)
   - Additionally it could be marked as optional/extra dependency, so the users of the library need to opt-in
   - Pylint could be replaced e.g. by a less permissive alternative like [ruff](https://github.com/astral-sh/ruff) so the reasoning about the required license is more straight forward
* Prysk needs to be clearly separated as development dependency

**Comment by Nicoretti** [comment]
Validation will be added later, initially we will just add [reporting](https://github.com/exasol/python-toolbox/pull/332) and later on extend on it if still required.
