### ISSUE TITLE
📚 Small documentation issues

### ISSUE THREAD

**Issue by ckunki** [exasol/python-toolbox#86]
# Summary
[Documentation of PTB](https://exasol.github.io/python-toolbox/user_guide/workflows.html) contains some issues that should be fixed.

# Details

1. File [doc/user_guide/workflows.rst](https://github.com/exasol/python-toolbox/blob/main/doc/user_guide/workflows.rst), section _2. Add the standard workflows to your project_ 
   * names command `tbox workflow install all` 
   * while it should be `tbx workflow install all` 

2. File [doc/user_guide/workflows.rst](https://github.com/exasol/python-toolbox/blob/main/doc/user_guide/workflows.rst), section _2. Add the standard workflows to your project_  should also mention that user needs to create folders in advance (optionally PTB could create the folders if not existing): 

```shell 
mkdir -p .github/workflows
``` 

3. File [.github/workflows/ci-cd.yml](https://github.com/exasol/python-toolbox/blob/main/.github/workflows/ci-cd.yml) contains 
```
  cd-job:
    name: Continues Delivery
```
while it should be **Continuous Delivery**

# Task(s)

- [x] Update documentation `doc/user_guide/workflows.rst`
- [x] Update File `.github/workflows/ci-cd.yml`
- [x] Bump version number
- [x] Update changelog

**Comment by Nicoretti** [comment]
apparently the current version of tbx check and creates the path for the workflow if necessary.
